<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class Cookies extends MY_Controller {
    
    public function __construct() {
        parent::__construct();
    }
    function _head_alter(&$head) {
        //add items to the header
    }
    function _styles_alter(&$styles) {
        //add necessary css to page header
        return add_style($styles, base_url().'frontend/core/css/cookies.css');
    }
    
    function _scripts_alter(&$scripts) {
        //add necessary JS
        return add_script($scripts, base_url().'/frontend/core/js/cookiebanner.min.js');
    }
    
    function _widget() {
        //contains information about the widget generated by this module
        $uri_segment = $this->uri->segment(1);
        $data = array();
        
        return ($uri_segment != 'admin') ? $this->load->view('view_cookies', $data, TRUE) : '';
    }
    
    function _install() {
        //method for installing any records or additional tables
    }
    
    function _config() {
        return 'This is the cookies module configuration page';
    }
    
    function accept() {
        //Save the users choice to accept cookies
    }
}