<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class Cookies extends MY_Controller {
    
    public function __construct() {
        parent::__construct();
    }
    function _head_alter() {
        //add necessary css to page header
    }
    
    function _scripts_alter() {
        //add necessary JS
    }
    
    function _widget() {
        //contains information about the widget generated by this module
        return '<p>Cookie compliance goes here</p>';
    }
    
    function _install() {
        //method for installing any records or additional tables
    }
    
    function _config() {
        return 'This is the cookies module configuration page';
    }
}