<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class Widget extends MY_Controller {
    
    public function __construct() {
        parent::__construct();
    }
    public function simple() {
        //Simple and static HTML widgets
    }
    public function dynamic() {
        //Dynamic widgets generated by fx. modules
    }
    public function menu() {
        //Widgets that represents menus
    }
}